language: minimal

env:
  - LLVM_VERSION=6.0
  - LLVM_VERSION=7
  - LLVM_VERSION=8
  - LLVM_VERSION=9 EXPERIMENTAL=1

script:
  - docker build --build-arg LLVM_VERSION=$LLVM_VERSION --build-arg EXPERIMENTAL=$EXPERIMENTAL --tag clang-$LLVM_VERSION .

after_success:
  - docker tag clang-$LLVM_VERSION floydci/debian-sid-clang:$LLVM_VERSION
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - docker push floydci/debian-sid-clang:$LLVM_VERSION
